from CB2325NumericaG1.erros import erro_numerico

def test_erro_numerico_simples():
    assert erro_numerico(4) == 4, "erro na funcao_erro_numerico"