def erro_numerico(a: int) -> int:
    return 2*a
